sudo: false
language: node_js
branches:
  only:
    - dev
    - master
node_js:
  - '8'
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
