sudo: false
language: node_js
branches:
  only:
    - new
    - master
node_js:
  - '10'
services:
  - mongodb
before_install:
  - npm i npminstall -g
install:
  - npminstall
before_script:
  - sleep 15
  - mongo football --eval 'db.createUser({user:"test",pwd:"test",roles:[{role:"dbOwner",db:"football"}]});'
  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'test'
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
