sudo: false
language: node_js
branches:
  only:
    - new
    - master
node_js:
  - '10'
services:
  - mongodb
  - redis-server
before_install:
  - npm i npminstall -g
install:
  - npminstall
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"test",pwd:"test",roles:[{role:"dbOwner",db:"football"}]});'
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
